name: æ›´æ–° kik-shards ğŸ”„

on:
  push:
    branches:
      - master
    paths:
      - '**.shard'
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
    # ç¬¬1æ­¥: æ£€å‡ºä»£ç 
    - name: æ£€å‡ºä»£ç  ğŸ“¦
      uses: actions/checkout@v2

    # ç¬¬2æ­¥: è®¾ç½®Pythonç¯å¢ƒ
    - name: è®¾ç½® Python ğŸ
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    # ç¬¬3æ­¥: å®‰è£…ä¾èµ–
    - name: å®‰è£…ä¾èµ– ğŸ› ï¸
      run: |
        python -m pip install --upgrade pip
        pip install -r auto-update-kikshards-json/kik-shards-requirements.txt

    # ç¬¬4æ­¥: æ›´æ–° kik-shards.json
    - name: æ›´æ–° kik-shards.json ğŸ”„
      run: python auto-update-kikshards-json/update_kik_shards_json.py

    # ç¬¬5æ­¥: æäº¤å¹¶æ¨é€å˜æ›´
    - name: æäº¤å¹¶æ¨é€å˜æ›´ â¬†ï¸
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add kik-shards.ini
        if ! git diff --staged --quiet; then
          git commit -m "æ›´æ–° kik-shards.ini"
          git push https://$GITHUB_TOKEN@github.com/WizisCool/KiKHanbot.git HEAD:master
        else
          echo "æ²¡æœ‰å˜æ›´æäº¤"
        fi
